### ISSUE TITLE
V1.1 Issue: Item boxes are being cut off and margins/prices cant be seen

### ISSUE THREAD

**Issue by baileyr12** [Belieal/flipping-utilities#1]
![image](https://user-images.githubusercontent.com/37287433/77486531-f4d56280-6dfd-11ea-8209-75a8c0e29e06.png)

I have tried reopening the client and updating the plugin. I'll try uninstalling the plugin and readding.

**Comment by Belieal** [comment]
Hi and thank you for the issue! 😄 

This bug seems to be because of the item name being too long to fit the top panel, and it expanding beyond the wrapper. I'll have fixed this for the next version.

For now, you will have to reset the items by pressing the reset button at the very top right.

**Comment by Belieal** [comment]
A fix for this has now been released to the plugin hub.
