### ISSUE TITLE
Can we make the offer timers go away??

### ISSUE THREAD

**Issue by xjazz207** [Belieal/flipping-utilities#102]
A new feature that just dropped was having the amount of time the offer has been in right on the item. Can we have an option to turn these off? I find them really distracting especially since they keep flashing green and red if I do too many option too quickly, and the white font really stands out too much. Obviously I know some people will like this feature, I'm just asking for an option to turn it off for the people who don't.

**Comment by zumaad** [comment]
yep, i am working on that. It will be toggle able by the config options of the plugin.
