### ISSUE TITLE
[BUG?] Logging into free to play world tracks items with correct icon but merges all "Members Object"

### ISSUE THREAD

**Issue by z0w13** [Belieal/flipping-utilities#109]
I have 2 accounts and sometimes end up logging into my main P2P acc on a F2P world, this causes all the items to be tracked as "Members Object" even though the icon is still correct.

I don't know if it's possible to still detect what item it actually is while on a F2P world but that would solve this issue.

**Comment by zumaad** [comment]
hmm that is interesting, I assume that only happens when an offer comes in for an item not currently in the flipping tab?

**Comment by z0w13** [comment]
If I recall correctly that is the case yes, if it's seen the item once already it'll track as usual

**Comment by zumaad** [comment]
ah I see, I'll check it out and let you know when its fixed!

**Comment by zumaad** [comment]
fixed
