### ISSUE TITLE
Gradle test failures

### ISSUE THREAD

**Issue by telans** [Belieal/flipping-utilities#11]
com.flippingutilities.FlippingPluginTest > initializationError FAILED
        java.lang.Exception: Method main() should not be static

    com.flippingutilities.FlippingPluginTest > initializationError FAILED
        java.lang.Exception: Method main should have no parameters

**Comment by Belieal** [comment]
Do you have any additional info regarding this issue?

**Comment by telans** [comment]
Not particually, I'm not familliar with java just thought it would be worth pointing out (assuming you made the test)

Occurs with `./gradlew build`

Full output: https://hastebin.com/adazovibil.cs

**Comment by Belieal** [comment]
Nah, that's on RuneLite. :)
