### ISSUE TITLE
Updated Buy Limits

### ISSUE THREAD

**Issue by satyrsaw** [Belieal/flipping-utilities#112]
Update the buy limits to the new ones from the last update, here are a list of the changes https://docs.google.com/document/d/1nusZDjZrajHwK6TRrJwB0dHkRUEQ88ZgUwq97G4QL5Q/edit.

**Comment by zumaad** [comment]
Thanks! I've been meaning to update these

**Comment by satyrsaw** [comment]
Cool thanks for the info! Any ETA?

**Comment by zumaad** [comment]
i can get it released this weekend probably, shouldn't be difficult :)

**Comment by satyrsaw** [comment]
Nice! I'm looking forward to it ^^

**Comment by zumaad** [comment]
just released
