### ISSUE TITLE
undo button or warning on delete

### ISSUE THREAD

**Issue by bektrs** [Belieal/flipping-utilities#113]
over the past 2 days me and one other guy in my cc have misclicked on the delete x on the plugin

a warning or undo button would be awesome
love the plugin

**Comment by zumaad** [comment]
thanks! :)   
is this delete on items in the statistics tab?

**Comment by bektrs** [comment]
Yes it’s a small red x only visage when you hover it I believe. I’m not at
my pc right now but I’ll have a look for you later.
I noticed it updated after I sent that message so it might already be
fixed.
Great job on the plug-in 👍

**Comment by zumaad** [comment]
fixed in latest release
