### ISSUE TITLE
Suggestion - High Alch prices

### ISSUE THREAD

**Issue by Rainyfaux** [Belieal/flipping-utilities#116]
Would it be possible to add high alching prices to the addon to check if it's better to flip or alch?

**Comment by zumaad** [comment]
For it to be better to alch, the sell price would have to be less than alch price - nature rune cost, which isn't the case most of the time. That is possible to add on, its just that the interface is already kind of space constrained which makes it difficult. I'll think about adding it in the future perhaps.
