### ISSUE TITLE
Client crash causes loss of history

### ISSUE THREAD

**Issue by chrstfer** [Belieal/flipping-utilities#117]
If the client crashes/doesnt exit gracefully, all history for that session seems to be lost. Can we mitigate this by having history written to the store periodically rather than just on session end?

**Comment by zumaad** [comment]
Yep, that can be done. I'm also looking for a way to stop the client from crashing due to memory errors (perhaps thats the crashing problem you are running into)

**Comment by chrstfer** [comment]
I think it probably is, the crashes happen most often when I'm at the GE. Do you have any suggestions?

**Comment by zumaad** [comment]
I'm not sure exactly whats causing it, I've started profiling the plugin with visualVm and it looks like there's a memory leak where memory taken by old GUI elements is not freed up which results in eventual OOMs. I'm working on fixing it, but i suppose in the mean time you can close shutdown the client periodically to free up the memory.

**Comment by chrstfer** [comment]
Can you put the memory usage somewhere in the UI in the meantime? To give a bit of warning when to restart.

**Comment by zumaad** [comment]
Should be fixed with the latest release
