### ISSUE TITLE
Manually adding transactions (ie, from trading on mobile) 

### ISSUE THREAD

**Issue by Spuddya7x** [Belieal/flipping-utilities#118]
Please make it possible to manually add transactions to the log.

**Comment by zumaad** [comment]
Hi, i'm currently working on this! Just really busy the past few weeks so i haven't been able to do much.

**Comment by Spuddya7x** [comment]
Hi mate, thats good to hear. Just want to apologise as my request sounded really rude. I wrote it at work as it popped into my head haha. If I knew how to write this stuff, I would help, but i have no idea. Thanks very much!

**Comment by zumaad** [comment]
haha no problem!

**Comment by zumaad** [comment]
closed cause this feature has been released :)
