### ISSUE TITLE
Price "N/A" SUGGESTION: Option to Check Margin by Buying 10 Items

### ISSUE THREAD

**Issue by Peridactite** [Belieal/flipping-utilities#119]
I've just started using the plugin but it has failed to show the price for the past 10 items I've checked. Instead it just shows "N/A". Only 1 of the 7 actually show the profit/roi/buy price. Am I doing something wrong or is this some kind of bug?

EDIT: I'm going to assume this is not a bug. Although the intended functionality was not clear to me upon first usage.

**Comment by Peridactite** [comment]
I don't know that it matters but I've tried with and without the "collect" button.

**Comment by Peridactite** [comment]
I figured out that the utility will only detect a price when you are buying/selling at the quantity of "1". It's a common strategy to buy/sell 10 or 100 of extremely cheap and low value items to throw off the other flippers. It would be fantastic if this could be an option in the settings or for the utility.

**Comment by Peridactite** [comment]
An alternative solution is to just allow users to manually set buy/sell price.

**Comment by zumaad** [comment]
Yea, that sounds like a good suggestion! I can work on an update later on where you can manually edit the margin prices and that would be reflected in the widget too along with anywhere else the margin prices are used

**Comment by wisnoskij** [comment]
I would really love the ability for this utility to work when buying any number if items. Maybe I am doing it wrong, but I "check margins" buy buying and selling the GE limit. And I would argue that if anything the ability to buy and then sell 10000 of an item is a more rigorous margin check, then checking with 1 item.

**Comment by zumaad** [comment]
That makes sense, its a very easy change too. I think i'll add a config option that people can toggle if they want offers of > 1 item to also count as margin checks.
