### ISSUE TITLE
Old UI with colour coded prices and times

### ISSUE THREAD

**Issue by Consistently-Inconsistent** [Belieal/flipping-utilities#123]
Could you please add an option to have the colour coded prices and times back.
The new update changed the entire UI and I sort of preferred the older version a bit more.
If not, is there a way to rollback to a previous version before this new UI ?

**Comment by SpiteH** [comment]
I'd like to know this too. There are too many numbers on each item so it's very hard to find the one you want to know.

**Comment by zumaad** [comment]
I added the color coding back in. When the RL dev team approves the plugin change, you'll be able to see it. Here is a preview:
![image](https://user-images.githubusercontent.com/21697386/100698621-866a7c00-335e-11eb-96b3-e00f443399c4.png)
