### ISSUE TITLE
Total profit not calculating properly

### ISSUE THREAD

**Issue by Kaybuh** [Belieal/flipping-utilities#128]
First off, love the plugin. I'm on a challenge flipping to a total of 1B... after the last update my total profit is not calculating properly. Some of my biggest flip items are showing negative margins (ex. Bandos Godsword -4,828,812gp (x1,144)). If you need any more info from me I would love to contribute. 

Thanks,
Kaybuh

**Comment by zumaad** [comment]
Hi! Could you dm me on discord at gaymersriseup#4026 so I can take a look at your logs and get some more info?

**Comment by Kaybuh** [comment]
I sent a friend request. It would not allow me to send a DM directly.

Thanks,
Kaybuh
