### ISSUE TITLE
favorite items quick search is not working

### ISSUE THREAD

**Issue by wigglepop** [Belieal/flipping-utilities#138]
I have set a few favorite items and it does not show when i type "1"

![image](https://user-images.githubusercontent.com/77034846/104140376-47632800-53ec-11eb-904d-0e144a635346.png)
![image](https://user-images.githubusercontent.com/77034846/104140383-5053f980-53ec-11eb-9eea-175267b93345.png)
![image](https://user-images.githubusercontent.com/77034846/104140404-619d0600-53ec-11eb-84c3-84e4bc287208.png)

**Comment by zumaad** [comment]
do you have ge fuzzy search on?
