### ISSUE TITLE
Flipping individual items into sets

### ISSUE THREAD

**Issue by yaowser** [Belieal/flipping-utilities#142]
Great plugin...can you guys also keep track of when people flip items into sets? for example, if you buy an armor set or dragonhide set separately and then put it into a set and sell the set, there is a significant margin. the tracker should also keep track of your revenue when flipping individual items into sets

not sure if this also counts, but if you put apples or onions into baskets, that is also set making and should be tracked in total revenue

what about converting staffs types into other staff types and then selling it?

---
optional/debatable:

skilling things into different things also should count, such as herblore item to item and xp conversion

what about high alchemy from the ge where you buy the item and runes and high alch them? would that count?

**Comment by zumaad** [comment]
Hi, thanks for the suggestion! This is something I am thinking about implementing in the future, but it would require a lot of work so no promises on when it will be released.
