### ISSUE TITLE
Use URL also for https://prices.runescape.wiki/

### ISSUE THREAD

**Issue by xescugc** [Belieal/flipping-utilities#148]
As the RuneLite is now also tracking the [Prices](https://oldschool.runescape.wiki/w/RuneScape:Real-time_Prices) as RSBuddy, would be good to add https://prices.runescape.wiki/ on the list of URLs

**Comment by zumaad** [comment]
Left comment in the PR, please take a look at it. I really appreciate you taking the time to solve this and submitting a PR!

**Comment by xescugc** [comment]
Perfect don't worry :) I was waiting for an update to see that but as I did not see I decided that I would do it and I assumed it was already an easy fix as it would most likely be the same as the other 2 (which it was at the end).

Happy to help and waiting for your PR haha.
