### ISSUE TITLE
All history from multiple accounts cleared from changing name on runescape.com

### ISSUE THREAD

**Issue by Lagflex** [Belieal/flipping-utilities#155]
n/a not sure what else to include.

**Comment by zumaad** [comment]
hey sorry for the late response, just saw this. Please dm me on discord at gamersriseup#4026, or join the flipping utilities discord and reach out to me. 

All the data should still be there, just go to .runelite/flipping and you should see the file for your old name on there. You can just change that file's name from your old name to your name (and delete the file created for your "new account")
