### ISSUE TITLE
[BUG] Quantity editor panel does not close when it's supposed to.

### ISSUE THREAD

**Issue by ColdMeekly** [Belieal/flipping-utilities#159]
![image](https://user-images.githubusercontent.com/20516479/120613015-18f6ef80-c456-11eb-8a38-53cb3093e828.png)

Steps to reproduce:

1. Choose an item to buy / sell.
2. Click "..." for the quantity editor.
3. Press "o" for the cashstack hotkey.
4. Move away from the GE clerk.

**Comment by zumaad** [comment]
interesting, I tried the exact same steps and couldn't reproduce it 🤔

**Comment by ColdMeekly** [comment]
I also cannot seem to reproduce after runelite updated to the latest commit. I'll mark it as resolved until someone encounters this again.
