### ISSUE TITLE
Ideas wanted for GUI

### ISSUE THREAD

**Issue by Belieal** [Belieal/flipping-utilities#16]
So I've gotten a few PMs where users have requested features that are already available in the tooltips of the labels in the panel. I recognize that this is a fault in the GUI, as many users find it non-obvious that the labels are hoverable. 

I'm a bit lost on how to make it easily recognizable that the labels do indeed contain important information in the tooltips and I wanted to hear the suggestions of anyone reading this.

So far, I've thought of adding underlined labels:
![image](https://user-images.githubusercontent.com/14042923/78666175-40e0d680-78d7-11ea-9848-81d6b2c5b31a.png)
However, I think this might look a little messy the more underlines that get added. I've also floated the idea of removing the tooltip all together and make it a label on the item panels instead. However, I think that adding, at times, unnecessary information is bad design as it would clutter the panels and make it hard to quickly interpret more regularly needed information.

Please let me know if you can think of a better way of doing this! 😄

**Comment by zumaad** [comment]
One thing I can think of is that the information conveyed by those tooltips is info you don't look at as often as something like the margin of the item. So this type of information could be moved to an expandable panel in the item panel (a "more info") panel or something like that. So if the user wanted, they could click on it and see things like when the ge limit will refresh, etc. That way, you don't clutter what's visible by default through adding a bunch of info that not everyone will look at it and you also make it explicit that there is more potentially relevant info in the panel if they expand it or something.

**Comment by nlruk** [comment]
Maybe once GE Limit = 0 it replaces the whole "GE Limit: numberhere" and shows a timer counting down the hours, minutes and seconds and once the 4 hours is over it will show the "GE Limit: numberhere"

**Comment by Belieal** [comment]
So I've been thinking of this for a little while and I think I will stick with a dotted underline but just for the GE limit for now. I believe this to be the most important information of all the tooltips however I also think that ultimately down the line what @zumaad suggests would be ideal considering that we may add additional information to the item panels in the future. When that time comes, I'll redesign it.

@nlruk I don't think it solves the issue of tooltips being too non-obvious. I do however think it's a really cool suggestion as it's way more informative than just showing the GE limit as being 0.
