### ISSUE TITLE
Top of settings panel is out of view

### ISSUE THREAD

**Issue by jevonsp** [Belieal/flipping-utilities#163]
![image](https://user-images.githubusercontent.com/8881225/127544872-59af51d5-cb52-4b4f-9d49-da9458f76515.png)

I'm not sure what I'm doing wrong (if anything), but I cannot get the top of this panel to show up ever

**Comment by zumaad** [comment]
Hmm, that's very odd. I tried it with various sizes of RL and it always works. Could you contact me on discord at gamersriseup#4026?

**Comment by jevonsp** [comment]
Hey! Totally forgot to come back and check. I figured out a hacky solution- you can drag the bottom of the window down until it fully shows on screen.
