### ISSUE TITLE
Flipping Utilities Doesn't Work Anymore

### ISSUE THREAD

**Issue by OsRs4E** [Belieal/flipping-utilities#165]
I don't know why but my plugin stopped working for some reason... what can i do to fix it?
A screen should pop up in the red square...

I really like this plugin!

<img width="844" alt="flipping" src="https://user-images.githubusercontent.com/97118657/148096768-74ee19bd-b481-4dd7-9797-b11b59c25841.png">

**Comment by zumaad** [comment]
made issue in the other repo
