### ISSUE TITLE
Grand Exchange Buying limit reached (Notification and 4 hour timer)

### ISSUE THREAD

**Issue by nlruk** [Belieal/flipping-utilities#18]
When an Item from the grand exchange has successfully been bought we get a notification in the chat.

Is it possible to get a similar notification when the 4-hour buying limit has been reset?

Can we also have a real-time 4-hour timer that is shown? So we can see in real time how many hours, minutes, seconds is left till we can buy that item again.

This will be extremely useful.

**Comment by Belieal** [comment]
Hi there and thank you for the suggestions! :)

> Is it possible to get a similar notification when the 4-hour buying limit has been reset?

This is a feature I'm considering as noted in the suggestions section of the frontpage-readme.

> Can we also have a real-time 4-hour timer that is shown? So we can see in real time how many hours, minutes, seconds is left till we can buy that item again.

Would you mind being a little more specific? As far as I can tell by this, you're requesting a feature that is already available in the tooltip of the GE limit on the item panel.
![](https://camo.githubusercontent.com/c54a6676916f5323321fb67aa3abcf25d3918fbc/68747470733a2f2f692e696d6775722e636f6d2f445054304158762e706e67)

**Comment by nlruk** [comment]
> Hi there and thank you for the suggestions! :)
> 
> > Is it possible to get a similar notification when the 4-hour buying limit has been reset?
> 
> This is a feature I'm considering as noted in the suggestions section of the frontpage-readme.
> 
> > Can we also have a real-time 4-hour timer that is shown? So we can see in real time how many hours, minutes, seconds is left till we can buy that item again.
> 
> Would you mind being a little more specific? As far as I can tell by this, you're requesting a feature that is already available in the tooltip of the GE limit on the item panel.
> ![](https://camo.githubusercontent.com/c54a6676916f5323321fb67aa3abcf25d3918fbc/68747470733a2f2f692e696d6775722e636f6d2f445054304158762e706e67)

Apologies for not being clear. I mean having a timer like below which is always shown when ge limit = 0

The tooltip that you implemented requires the user to do something to see how long they've got left. I would like to be able to use your search feature and be able to see straight away how long left instead hovering over ge limit



![giphy](https://user-images.githubusercontent.com/63312904/78866471-59680280-7a37-11ea-9432-2c1fb0c2e01c.gif)

**Comment by stoddy15** [comment]
https://github.com/runelite/runelite/pull/11257

https://imgur.com/a/qvVTEP7

**Comment by zumaad** [comment]
closed. You finally got your ge limit timer with the new panel design :)
![image](https://user-images.githubusercontent.com/21697386/100535422-5b591e80-31de-11eb-9415-ced4014b0518.png)
