### ISSUE TITLE
some ideas

### ISSUE THREAD

**Issue by zumaad** [Belieal/flipping-utilities#20]
1.  Make widget automatically undercut and overcut by 1 gp
2. Make widget prices adjust (depending on how expensive the item is), if the item is not buying/selling. Example: You are flipping pegasian boots and none have sold for the past 15 mins, so the widget gets automatically adjusted to display the selling price - 10k. This will have to be thought out more and very flexible as margins vary a lot, the rate at which certain items buy and sell vary a lot, etc.
3. Have a concept of an item list which you can build. As you flip items, it crosses them off the list or something similar.
4. item suggester based on how much money you have, buy rates, etc. This involves some data scraping from the GE, which I've already done in some small capacity before.

**Comment by Belieal** [comment]
1. I was thinking about adding buttons with 0.0001%, 0.001% etc. price incrementors and decrementors (obviously ceiling the value), but I'm not very experienced with high value items (measly 50M cash stack ;_;), so I'm not sure if this how this works with those items. Perhaps you have some more insight into this? Would it be better than just having regular +1, +100 etc. buttons just like the GE offer setup?

2. & 4.) I'm very interesting in how we can get the salerate of items. I know that Runelite has services for GE prices (ItemService), but I'm quite honestly a little lost on how it all works. I think that salerate could potentially be a thing we add to the item panel or even as a widget to the GE offer setup window.

3. I'm pretty sure we have the same idea with 

> Grouped checklist tab with import and export features so you can keep track of the items you like to flip most!

from the suggestions section in the readme. ;)

**Comment by zumaad** [comment]
1.  Even with high value items I just undercut with 1 gp as functionality it is the same. In fact, locally I made the widget always display the selling price 1gp lower than it is actually is.  I was thinking maybe this could be the default state of the widget as you typically always undercut when flipping.

2 &4, so for buy/sell rates we could scrape this url http://services.runescape.com/m=itemdb_oldschool/Lobster/viewitem?obj=379, and extract the relevant information out of the page. There is also a web api which serves just json at http://services.runescape.com/m=itemdb_oldschool/api/catalogue/detail.json?item=379, which is much easier to get relevant data from, but it only has the current price of the item, not the buy rates.

I was thinking that we can have a script that scrapes the data for relevant items (price, buy rates) using the url above (the first url) and save that data to a file hosted somewhere (it can be on GitHub) and the plugin can simply make a request to that file at https://github.com/belial/flipping-utilities/itemInfo.json, save the contents in memory like in a array/hashmap,  and then maybe there could be a class built for querying that data appropriately.

Alternatively, we could scrape the data, push the file to your repo and stick the file in the resources folder or something and that way people who use the plugin would actually have a copy of it locally. The problem with that is that every time  we want to change the file you would have to republish the plugin, whereas if its hosted somewhere we can just make the change to it and since the plugin makes a request to wherever its hosted, it will get the most recent copy.

**Comment by Belieal** [comment]
I've been researching a bit on how we could feasibly do this and I think we could use the Wikia for this purpose. It seems to have the volume for every tradable item stored in an ```Exchange``` module.  

Example: https://oldschool.runescape.wiki/w/Module:Exchange/Lobster (Item name is case-sensitive)

We can use the ```Special:Export``` feature to get the xml of the page. 

Example: https://oldschool.runescape.wiki/w/Special:Export/Module:Exchange/Lobster

Then I assume we can use `DocumentBuilder` to parse the xml to a `Document` and lastly use `getElementsByTagName` to extract the volume data.

**Comment by zumaad** [comment]
Oh yeah that works much better! How did you find that lmao

**Comment by Belieal** [comment]
Good old-fashioned google-'til-you-find-something with a dash of patience! :D

**Comment by zumaad** [comment]
btw, when are you usually on? I swear I never see you logged in lol

**Comment by Belieal** [comment]
You mean in-game? I usually have my private off since I keep logging in and out when I'm testing things. Don't want to spam my friends' PMs with log in/out messages 😄

**Comment by nlruk** [comment]
I'm not sure if its a bug but when you press the widget can you also make it press enter because if you don't and press confirm it doesn't change the price !

<img width="748" alt="Screenshot 2020-04-11 at 03 27 45" src="https://user-images.githubusercontent.com/63312904/79033241-98679680-7ba4-11ea-9b8b-661d3a6b0e45.png">

**Comment by Belieal** [comment]
> I'm not sure if its a bug but when you press the widget can you also make it press enter because if you don't and press confirm it doesn't change the price !

Unfortunately, that is against the Jagex TOS.

> ^ PS: Can undercut be optional as I never do it on high volume items :)

I think the idea going forward is to expand the widget such that there will be incrementors and decrementors, much like the way the GE setup window is designed.

![image](https://user-images.githubusercontent.com/14042923/79033356-e2a14580-7bad-11ea-8e3e-4d7683390b91.png)

You would be able to select the middle section to just keep the buy/sell price or you can click the +/- to undercut by 1. Pressing it again would further increment/decrement the price etc.

**Comment by telans** [comment]
As a seperate GUI idea, perhaps it would be nice to show the "GP Needed" for a flip (behind a setting perhaps)? Would be useful when dealing with a bank < 20M

**Comment by Belieal** [comment]
Yeah, I think it's a wonderful idea. We could incorporate the already present widget in the quantity input to set it to, whichever is lower, remaining GE limit or how many you can afford.
