### ISSUE TITLE
Show the last time you bought/sold an item that wasn't a margin check

### ISSUE THREAD

**Issue by zumaad** [Belieal/flipping-utilities#24]
So currently, we show the last time you margin checked an item (if the margin check didn't happen when the item was frozen). I find myself wondering often, when was the last time this item bought? Cause if it was long ago, I want to drop down the price a little. So adding info about when was the last time you bought/sold an item, regardless of margin check and regardless if the item was frozen could be good.

I don't know where we would house this info, so we'd have to think about this so that we don't clutter the FlippingItemPanel.

**Comment by Belieal** [comment]
I think this could be done with an overlay on the offer slots in the GE interface.

**Comment by zumaad** [comment]
oooh I didn't even think of that, that is really slick
