### ISSUE TITLE
Unfreezed margins should only re-freeze when both upper & lower has been updated

### ISSUE THREAD

**Issue by telans** [Belieal/flipping-utilities#26]
When using auto-freezing, the item waits for both a buy and a sell price before the margins are freezed.

However, when manually unfreezing an item (for example to update the margins) the item is re-freezed without waiting for an updated buy price, leaving incorrect/partially outdated margins.

I believe that an item should only re-freeze when both the buy and sell price has been updated.

**Comment by zumaad** [comment]
Nice suggestion, I agree. I can get on this. @Belieal, should I push this update to the statistics-tab when I'm done?

**Comment by Belieal** [comment]
Sure! ^^

**Comment by telans** [comment]
On a side note - is there an easier way to sync changes with this repo for building within RuneLite? At the moment I've just symlinked the required files with a commit on top making it compatible with RuneLite.

For updates I just rebase my commit on top of any changes here.

Cheers

**Comment by zumaad** [comment]
I used to develop within the official runelite repo (my fork of it) and paste my files back and forth....now I develop in this fork's environment and I can just fetch, merge, etc. Since this fork is set up as a Gradle project, you can just import it in IntelliJ as a Gradle project. It has all the dependencies required such as the runelite client and such. Thats the easiest way to develop.

**Comment by zumaad** [comment]
its Fixed in #27

**Comment by telans** [comment]
@zumaad 

Apologies for pinging you, would you mind showing how your project modules are set up? I'm not familliar with IntelliJ/maven, the only way I can figure out how to get the plugin building with RuneLite is the method I mentioned beforehand.

Thanks

**Comment by zumaad** [comment]
@telans , no problem! So I use IntelliJ to develop as is recommended by the Runelite dev team. My knowledge of java tooling is quite limited, so I can only really set up the project in the context of IntelliJ as it helps with a lot.

This is how I set everything up. 
1. Get IntelliJ if you don't have it.
2. Start a new Project and select "project from version control", select git from the dropdown and give the url you would use to clone the repo.
3. Now all the files will be imported in IntelliJ, but you won't be able to run the project. Typically, a popup should show up, saying "import Gradle project". Click on this and wait for it to finish. Gradle will install all the dependencies the code requires to run.
4. Try to run the code by going to the test folder and running the FlippingPluginTest.
5. If the code fails to compile and it gives you a bunch of errors like "can't find symbol", etc. Then go to file -> invalidate caches/restart. And then try running the FlippingPluginTest again.

Good luck and let me know if it works!

**Comment by telans** [comment]
Thank you very much, I only just managed to figure it out myself (was stuck before running "FlippingPluginTest"). Turns out that fine-comb reading the wiki is actually useful! <sup>_sarcasm_</sup>

What you've written is still probably the clearest way I've seen it described so far though, very helpful thanks. (For others I assume too)
