### ISSUE TITLE
Add toolbar to flipping panel

### ISSUE THREAD

**Issue by baileyr12** [Belieal/flipping-utilities#28]
An option to unlock all the margin locked items would be great. There have been a few instances where I forgot to unlock the margin before checking. It's not a major issue, but if you're bored and needed a nice QOL feature this would be great ;) # #

**Comment by zumaad** [comment]
Hmm this would be pretty useful and easy to add in, just have to figure out how to add it in without cluttering existing stuff. @Belieal, any ideas?

**Comment by Belieal** [comment]
Perhaps we could move the clear button below the search bar and have a toolbar of sorts with different features that affect all flippingitems globally.

**Comment by zumaad** [comment]
sounds good 👍

**Comment by baileyr12** [comment]
@Belieal here's a little concept art I made! 
![image](https://user-images.githubusercontent.com/37287433/79078563-c1844600-7cce-11ea-9164-34ac7284393e.png)

**Comment by Belieal** [comment]
That looks amazing! I absolutely love the icons. I would love to use them! 😄

**Comment by zumaad** [comment]
Man that looks awesome lol. I made the methods to freeze and unfreeze items #31 . I tried to make the toolbar UI but as usual my UI comes out looking like garbage so I abandoned that effort.

**Comment by nlruk** [comment]
> @Belieal here's a little concept art I made!
> ![image](https://user-images.githubusercontent.com/37287433/79078563-c1844600-7cce-11ea-9164-34ac7284393e.png)

that looks great. just an idea is it possible to change the GE limit tooltip to "you need x amount of gp to buy the limit".

and have the timer on the interface at all times so it's not a tooltip. it shouldn't be hidden!

**Comment by Belieal** [comment]
> is it possible to change the GE limit tooltip to "you need x amount of gp to buy the limit".

We could do this, however I think it would be sufficient to expand the quantity input widget to include a button to set the quantity to what you have the money for.

> and have the timer on the interface at all times so it's not a tooltip. it shouldn't be hidden!

I believe you've already suggested this. #18

**Comment by Belieal** [comment]
@baileyr12 We would love to use the icons you have in your concept, would you be able to upload them if they're copyright-free? :)

**Comment by baileyr12** [comment]
> @baileyr12 We would love to use the icons you have in your concept, would you be able to upload them if they're copyright-free? :)

Most of those icons i just grabbed off google to use as an example, the others I made in photoshop. But here are some free icon .svg files I grabbed from [FontAwesome](https://fontawesome.com/icons?d=gallery&q=perce&m=free). I have used these in a lot of my web app classes! Hope this helps!
[Flipping Icons.zip](https://github.com/Belieal/flipping-utilities/files/4478262/Flipping.Icons.zip)

If these don't work I can probably design some!
@Belieal
