### ISSUE TITLE
I added functionality for deleting items :) 

### ISSUE THREAD

**Issue by zumaad** [Belieal/flipping-utilities#3]
![delete](https://user-images.githubusercontent.com/21697386/77816723-6d0c8400-709b-11ea-9523-d43ea915e5f1.gif)

thats a gif of it working. If you like it, I'll clean up the code and I can submit a pull request. I can also contribute a readme to getting started developing on this tool if you want- for newcomers who want to contribute.

**Comment by Belieal** [comment]
Apologies for the delay - been a bit busy over the weekend.

I really appreciate the amount of effort you've put into this, but I've actually just pushed the feature to the master branch that I've had working for a few days. Please check it out and see if it works how you intended it to! 😄 

As for the readme - I am very new to managing contribution projects and I have pretty limited knowledge of coding in general, so I have a hard time expressing the details of how the plugin is coded. If you'd like to contribute that I would be very grateful! 🙂

**Comment by zumaad** [comment]
I just pulled and checked it out. The hover functionality is a lot better than my static icon LOL, its really good!
