### ISSUE TITLE
[Statistics Tab] Ideas wanted for sub information

### ISSUE THREAD

**Issue by Belieal** [Belieal/flipping-utilities#33]
Heya!

I've recently pushed the statistics tab with added functionality to some sub information that I thought could be useful. This is what it looks like today:

![image](https://user-images.githubusercontent.com/14042923/79093893-fdaeb980-7d55-11ea-89b3-ff6f1dd0d37f.png)

The sub infos, that display general statistics about your total trade history, are shown below the total profit.
But I'm wondering, what stats do you think fits on the sub info panel? 😃 

Suggestions that have been implemented so far:

Added for v1.3:
- [x] Color gradient for ROI.
- [x] Dynamic total profit coloring
- [x] Total quantity of items flipped
- [x] Largest margin (Handled by stat item sorting)
- [x] Add option for 4 hour time interval
- [x] Most common item flipped
- [x] Total time flipping (Record total time with incomplete trade offers?)

Will *possibly* be added in a coming update:
- [ ] Average price and profit per flip.
- [ ] Average time to complete flip (After  #24)
- [ ] Chat commands

**Comment by telans** [comment]
I reckon average price & profit per flip would be nice to see, and might be nice to see a color gradient for ROI on this tab too.

Also perhaps there could be a setting for the "Total Profit" color matching that of a cash stack? i.e 0-100k = yellow, 100k-10M = white etc

Looks great as it is already though

**Comment by baileyr12** [comment]
A few ideas:
- Total Items Flipped
- Largest Profit Margin(or largest profit made on a single flip, something like that)
- Most common item flipped
- total time flipping?(idk how you would track when someone was flipping or not)
I'll add more when I'm not sleep deprived and tired from taking exams and doing homework lol

**Comment by telans** [comment]
> total time flipping?(idk how you would track when someone was flipping or not)

Average time to complete a buy / sale would go well with this

**Comment by nlruk** [comment]
A few ideas:

- Daily, weekly and monthly profit
-  Could we have a command like !flip so when we can type it in a flipping cc or public chat so we can compare our statistics to others
-  5 top items, 5 worse items, and average flip duration.

Love how active this development is !

**Comment by Belieal** [comment]
Thank you for all the suggestions, guys! 😄 I realize that this may become be a long term project of adding additional sub statistics. I'll go ahead and do the ones that should be pretty easy to make for now, so I can focus on what will be the stats for individual flips. I believe that will be the final feature that is added before release of v1.3! 🎉

**Comment by Belieal** [comment]
@nlruk 

> Daily, weekly and monthly profit.

This is already handled by the combobox at the top, where you will be able to select what time interval you want to show stats for! :)

> 5 top items, 5 worse items, and average flip duration.

I think this may already be handled by the not-yet-implemented stat item panels that will show up at the bottom (just like the main flipping UI). These you will be able to sort by highest profits and flip duration, if we are adding that.

> How about a separate tab for a leaderboard that resets every week displaying their rsn? Every Monday it will reset so we can try again to rank top 5. Would be interesting to see the best flippers.

This would require us to collect data from other users, which means it could very easily be spoofed if you have the slightest know-how.

**Comment by nlruk** [comment]
> This would require us to collect data from other users, which means it could very easily be spoofed if you have the slightest know-how.

That is such a shame I would hope the flipping community wouldn't do that. Couldn't you find a way to moderate the top 3 manually in-game? and if shown to cheat you could ban them from the leaderboard.

Anyway, it was just an idea. It would be so interesting! I know Syratube would place top 3 😄

**Comment by Belieal** [comment]
Well, that would require updates that need to be reviewed by RuneLite. I don't think the devs would be super appreciative with me spamming their PRs. :P 
Even then, I would have a very hard time actually figuring out if they're spoofed or not. Since almost all elements in the game can be spoofed, just like changing the HTML with inspect element in Chrome, we can easily make things like this:
![image](https://user-images.githubusercontent.com/14042923/79132193-28c2f880-7daa-11ea-9f76-812c2e9f7739.png)
With just the standard RuneLite dev tools.

And trust me, there are plenty of people that would love to be number 1 and would do anything to get it...

**Comment by Bautista-Baiocchi-lora** [comment]
Will stat tab track all your flips via a CSV file? Would be great since the user could then use that CSV for other things.

**Comment by Belieal** [comment]
> Will stat tab track all your flips via a CSV file? Would be great since the user could then use that CSV for other things.

All flips are saved within a JSON file, that you can access from the `settings.properties` file stored within /Users/$user$/.runelite/profiles/$your_runelite_username$. I don't think it would be too difficult to convert that to a .csv file.

It would be cool to make a dedicated csv exporter in the future though. :)

**Comment by Bautista-Baiocchi-lora** [comment]
> > Will stat tab track all your flips via a CSV file? Would be great since the user could then use that CSV for other things.
> 
> All flips are saved within a JSON file, that you can access from the `settings.properties` file stored within /Users/$user$/.runelite/profiles/$your_runelite_username$. I don't think it would be too difficult to convert that to a .csv file.
> 
> It would be cool to make a dedicated csv exporter in the future though. :)

Awesome, JSON format is good enough. Don't think CSV exporter is worth the dev time as of now.

**Comment by Bautista-Baiocchi-lora** [comment]
@Belieal do you have a discord I could contact you at?
