### ISSUE TITLE
Track an items margin history

### ISSUE THREAD

**Issue by Bautista-Baiocchi-lora** [Belieal/flipping-utilities#39]
It would be awesome if the plugin could track every individual margin check separately. This would allow the user to look back through the margin check history of an item based on date. Gives a good idea of how the item's price is moving. This could have great value in the statistics tab.

**Comment by Belieal** [comment]
Hi there and thank you so much the suggestion!

I absolutely agree with you - I think this would be an awesome addition to it. We can pretty easily mark the trades we thought were margin checks and show this to the user in the trade history. We may even be able to dedicate a button you would press to only show the margin checks on the lowest layer of the stat panel.
