### ISSUE TITLE
Git tags for the releases

### ISSUE THREAD

**Issue by Baklap4** [Belieal/flipping-utilities#49]
I'm currently missing the git tags for this repository as seen in the `README.md`
there are currently a few versions available;

* v1.0 - Plugin added!
* v1.1 - GE limit tracking added.
* v1.1.1 - 12 hour format for clocks and various bug fixes.
* v1.2

As for most projects i'd suggest using [semantic versioning](https://semver.org/) for this in the form of: [major].[minor].[patch]

The tags can be easily added to the repo by using the following git command;
`git tag -a [VERSION] [COMMIT-SHORT-SHA] -m "[MESSAGE]"`

Once all tags are added locally you can review them:
`git show-ref --tags`
Once alright, you can push them using `git push --tags`

As for this repo this script would suffice:

```
git tag -a v1.0.0 2eb33c6b6cd6ba2b50e529bfa6fa7707c6f495a6 -m "Plugin added!"
git tag -a v1.1.0 b1c453f3556496315d31c8616ab34133c4a92aac -m "GE limit tracking added."
git tag -a v1.1.1 41b0b80f530f104cc20fa0ab088d632f21cfcb21 -m "12 hour format for clocks and various bug fixes."
git tag -a v1.2.0 9f47b6b6663c09eac0133a8b25e7124fd78f5321 -m "Release 1.2.0"
```

**Comment by Belieal** [comment]
This is very interesting, thank you for bringing it to my attention! I'm a complete noob to Git (I've somehow been able to avoid the bash terminal during all this time 😄 ), so I've never even heard of this. 

I'll definitely look into the link you provided and see if I can figure out how to get this sorted.

**Comment by Baklap4** [comment]
Then in the releases of github you can add release notes to those tags :)

**Comment by Belieal** [comment]
I've now created the tags for the previous versions along with their commit hashes in accordance to how they were published on the RL plugin-hub, just like you mentioned. In coming versions, I'll continue to add tags and releases from now on. I don't think it's necessarily needed or relevant to add releases for the previous (and rather primitive) versions. 

Thank you so much for letting me know and teaching me about this. I love learning new things and I've still got lots to learn from Git! :)

**Comment by Baklap4** [comment]
Great thanks a lot! :)
