### ISSUE TITLE
Not tracking Ghrazi rapier

### ISSUE THREAD

**Issue by BlackFalcons** [Belieal/flipping-utilities#56]
I tried to flip the Gharazi Rapier but it did not track any of the sales or purchases.

**Comment by Belieal** [comment]
Hi there, and thank you for the issue! :)

Is it just the Gharazi rapier that doesn't track or do other items work fine? Is the selected time span within both the purchase and sale of the item? If you still have the client.log when this occurred, would you mind sharing it, using [pastebin](https://pastebin.com/)?

**Comment by BlackFalcons** [comment]
It seems to be working now.
