### ISSUE TITLE
Plugin no longer populating flips

### ISSUE THREAD

**Issue by UserID3** [Belieal/flipping-utilities#58]
As of this morning I noticed that my flips are no longer populating the plugin list and it seems to just be stagnant.

**Comment by nlruk** [comment]
> As of this morning I noticed that my flips are no longer populating the plugin list and it seems to just be stagnant.

Maybe a screenshot or more information can help @Belieal replicate this bug

**Comment by Belieal** [comment]
Hi there @UserID3!

Was the plugin working fine yesterday or the day before? Would you be able to share the client.log?

To find the logs, you can do one of the following:
- Open the screenshot directory by right-clicking Camera button, navigate 1 directory up, then open logs folder.
- Navigate to %userprofile%\.runelite\logs on Windows or $HOME/.runelite/logs on Linux and macOS.

**Comment by Belieal** [comment]
I'm gonna close this since the author hasn't provided any more information and a new version of the plugin has been released.
