### ISSUE TITLE
Make the "focus view" more intuitive

### ISSUE THREAD

**Issue by Bitz** [Belieal/flipping-utilities#63]
It might be nice to see more information shown in the focus view (when you search for an item and have a buy window open, the "Flipping" tab usually focuses on just the item you're looking at)

Mockup:
![image](https://user-images.githubusercontent.com/2023016/81882104-dcf99f80-955f-11ea-8f16-9ecfc27d8829.png)

Ideally I'd like to see recent trades for the specific item. It seems that we do log and display this information now in the Statistics tab, so having it also displayed here might be nice. 

I expected to not care about the stats tab but it's so nice omg.

**Comment by Belieal** [comment]
Hi there and thank you for the suggestion! :)

That's a really neat idea, and I doubt it would be too much work adding the trade history to items on the flipping panel. I believe the flipping panel as a whole needs a bit of a redesign, so perhaps this suggestion would be implemented there. ^^
