### ISSUE TITLE
Plugin crash

### ISSUE THREAD

**Issue by Bitz** [Belieal/flipping-utilities#64]
I believe a trade was being updated in the background while I was in the middle of creating another buy offer.
Upon doing this the plugin became unresponsive- it sat on the same screen and no longer responded to automatic events like creating a buy offer. 

I assume it is related to two seperate threads attempting to modify the data storage json at the same time. I'm sure string writers are not thread safe in that way. 

Please see the stack trace related to the crash below:

> 2020-05-14 01:43:02 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
> java.util.ConcurrentModificationException: null
> 	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
> 	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
> 	at net.runelite.client.plugins.flippingutilities.ui.statistics.StatsPanel.lambda$rebuild$3(StatsPanel.java:444)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
> 	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
> 	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
> 2020-05-14 01:43:21 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
> io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.reflect.InvocationTargetException
> 	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
> 	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:83)
> 	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
> 	at io.reactivex.rxjava3.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onNext(ObservableDoFinally.java:80)
> 	at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:63)
> 	at io.reactivex.rxjava3.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
> 	at com.jakewharton.rxrelay3.PublishRelay$PublishDisposable.onNext(PublishRelay.java:179)
> 	at com.jakewharton.rxrelay3.PublishRelay.accept(PublishRelay.java:144)
> 	at com.jakewharton.rxrelay3.SerializedRelay.accept(SerializedRelay.java:57)
> 	at net.runelite.client.eventbus.EventBus.post(EventBus.java:115)
> 	at net.runelite.client.callback.Hooks.post(Hooks.java:175)
> 	at client.onGrandExchangeOffersChanged(Client.java:1230)
> 	at client.hl(Client.java:6847)
> 	at client.fj(Client.java:2806)
> 	at client.au(Client.java:1113)
> 	at br.ab(GameShell.java:336)
> 	at br.run(GameShell.java:315)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.reflect.InvocationTargetException: null
> 	at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.runelite.client.plugins.Plugin.lambda$findSubscriptions$1(Plugin.java:96)
> 	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
> 	... 15 common frames omitted
> Caused by: java.util.ConcurrentModificationException: null
> 	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
> 	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
> 	at net.runelite.client.plugins.flippingutilities.ui.flipping.FlippingPanel.updateActivePanelsGePropertiesDisplay(FlippingPanel.java:364)
> 	at net.runelite.client.plugins.flippingutilities.FlippingPlugin.onGrandExchangeOfferChanged(FlippingPlugin.java:408)
> 	... 20 common frames omitted
> 2020-05-14 01:45:45 [Client] INFO  n.r.c.p.f.TradePersister - flipping directory already exists
> 2020-05-14 01:45:45 [Client] INFO  n.r.c.p.f.TradePersister - trades.json already exists

What is somewhat noteworthy is that after toggling the plugin off and on again, the Statistics tab data repopulated with values I had previously deleted around 30 minutes prior.

**Comment by zumaad** [comment]
It is because the we make updates to the GUI in a thread separate from the main thread and the list being used to rebuild the panels (in another thread) was modified by an incoming offer while it was being iterated through.

```
for (FlippingItem item : tradesList)
```

that is where the concurrent modification exception was thrown.  The crux of the problem is that it is the same reference -.-, so a modification in the main thread (when an offer comes in) affects the list being iterated through in another thread, hence throwing the concurrentmodifcation exception. The fix is very easy and it will be patched in 1.3.1. Thanks for bringing this up and providing the stack trace!

btw, if you have multi account functionality enabled and encounter this problem, it might be fixable by changing the view by selecting a different account from the dropdown menu (if you have one). That will force a rebuild and unless another offer modifies the list while its being used to rebuild the panels, it should fix the plugin being stuck. That's just a hack of course, the patch will fix it for good :)

**Comment by Bitz** [comment]
Ah! I was close! Multithreading is no fun.
