### ISSUE TITLE
Macbook Pro Touch bar support 

### ISSUE THREAD

**Issue by nlruk** [Belieal/flipping-utilities#65]
Hello,

Loving the recent updates!!!

Could you please display statistics and GE timer on the Macbook Pro Touch bar?

https://github.com/Thizzer/JTouchBar

![emoji](https://user-images.githubusercontent.com/63312904/81916554-dd2f8480-95cb-11ea-919d-52fca50d5ef4.png)
<img width="787" alt="Screenshot 2020-05-14 at 10 31 05" src="https://user-images.githubusercontent.com/63312904/81918577-8f684b80-95ce-11ea-9e4d-a834e18661e3.png">
![eemoji pac](https://user-images.githubusercontent.com/63312904/81916600-e7518300-95cb-11ea-8454-729f7e54faf0.jpg)

**Comment by Belieal** [comment]
This is a bit difficult for me to add as I don't own a Macbook with a touch bar but either way, we'd need to use a third party dependency, which I don't think RuneLite allows on their external plugins.

**Comment by telans** [comment]
sad days for macos laptop touchbar third party runescape client external plugin development
