### ISSUE TITLE
bug with margin views 

### ISSUE THREAD

**Issue by ConanWolf** [Belieal/flipping-utilities#66]
![image](https://user-images.githubusercontent.com/53108517/82088278-7095b200-96bf-11ea-8fab-60d6a391b63c.png)

i already did the 5% up and 5% down and everything i even made one flip already... but then it reset... idk what happened, can you allow manual input?

**Comment by Belieal** [comment]
Heya!
This isn't normal behavior, so would you be able to share your client.log during which this happened? It may be a part of an issue we plan to fix in 1.3.1. :)

To find the logs, you can do one of the following:
- Open the screenshot directory by right-clicking Camera button, navigate 1 directory up, then open logs folder.
- Navigate to %userprofile%.runelite\logs on Windows or $HOME/.runelite/logs on Linux and macOS.

**Comment by Belieal** [comment]
I'm gonna close this since the author hasn't provided any more information and a new version of the plugin has been released.
