### ISSUE TITLE
Suggestion Undercutting

### ISSUE THREAD

**Issue by JetFlightGit** [Belieal/flipping-utilities#68]
Fell in love already with this app.
I really like that you can add pricing and ge limits with just a click and enter.

I do miss the option though to set a value offset by 1 or 2. Since my english is not that good i show u in a picture:
![image](https://user-images.githubusercontent.com/46763079/82269906-5a178100-9973-11ea-9678-dfb7fa2cf767.png)
Similar for the price as well, or make 2 buttons both that can be customized in option. So if someone likes to undercut the price by 10 and 100 mainly they can choose that.

Hope that makes sense, somewhat.

best regards,
Jet

**Comment by Belieal** [comment]
Glad you like the plugin!

This is going to be something we're planning to add as part of the the widget expansion slated for v1.4.0. :)
