### ISSUE TITLE
"Time since last update" in Grand Exchange interface

### ISSUE THREAD

**Issue by Bitz** [Belieal/flipping-utilities#76]
It would be nice to see some level of offer tracking so we can know when an offer has stagnated. 

Basically, I assume we can probably track offers progress on a per slot basis. In doing so, can we then show the time that has since elapsed since the last item for a specific order has updated?

Mock up: 
![image](https://user-images.githubusercontent.com/2023016/83338111-e472b580-a28e-11ea-9286-66481b09f739.png)

**Comment by zumaad** [comment]
Check this out haha

https://github.com/Belieal/flipping-utilities/pull/73, its still a work in progress

**Comment by Bitz** [comment]
Oh wow, you guys are awesome, more than a week ahead of me with your feature implementations 😁
Closed as is already in progress.
