### ISSUE TITLE
Malformed URL request used when visiting "platinumtokens.com" for specific items

### ISSUE THREAD

**Issue by Bitz** [Belieal/flipping-utilities#78]
Replication steps: 
As far as I can tell, it currently happens with one item, `Sanguesti staff (uncharged)`
1. Margin check the item
2. Attempt to navigate to platinumtokens.com using the context menu
3. Notice the URL is:
``https://platinumtokens.com/item/sanguinesti-staff-u-n-c-h-a-r-g-e-d``
Expected:
``https://platinumtokens.com/item/sanguinesti-staff-uncharged``

The issue is that the url builder is missing the excluded word `uncharged`:

https://github.com/Belieal/flipping-utilities/blob/5bbc493d2ec3299a9722dbbf14eec04d9b31a102/src/main/java/com/flippingutilities/ui/UIUtilities.java#L69

**Comment by Belieal** [comment]
Thanks for the report, I'll see if I can find any other suffixes that need to be added as well.

**Comment by zumaad** [comment]
closed cause done
