### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ArjanStudent** [Belieal/flipping-utilities#93]
An issue I occurred with this plugin ( which might just be me ) is that it's very easy to delete trade history in statistics. I've done this a few times on accident since the delete section takes up a big part of the block and it would be nice to have a confirm for this or have a delete option with right click instead.

Thanks!

**Comment by zumaad** [comment]
Just to clarify, i assume you are referring to the "X" icon seen below?
![image](https://user-images.githubusercontent.com/21697386/86288378-d24ea480-bbb7-11ea-93e9-7c9927b59fd1.png)

If so, i think we could definitely add a warning/additional confirmation before you hit delete. Thanks for the suggestion!

**Comment by zumaad** [comment]
closing cause this was added
