### ISSUE TITLE
Several seconds freeze almost every time I switch to the "Statistics" tab

### ISSUE THREAD

**Issue by Raisoshi** [Belieal/flipping-utilities#94]
Issue as in the tittle, my game freezes completely and so does runelite, coming back about 10-15 seconds later, if I switch to "Flipping" and back to "Statitistics" it happens again. Once I'm in the tab everything works fine, it's just whenever I click on "Statistics".

Is there any more info I can provide? Like a log I can export or something?

**Comment by zumaad** [comment]
Hi, sorry for the late reply. What time frame are you selecting when you switch to the statistics tab? Cause if you are selecting the "all" time frame and you have a lot of flips, it has to render all the info, which can take some time.

**Comment by Raisoshi** [comment]
> Hi, sorry for the late reply. What time frame are you selecting when you switch to the statistics tab? Cause if you are selecting the "all" time frame and you have a lot of flips, it has to render all the info, which can take some time.

Hi, no worries, thank you for replying!

It doesn't matter what time frame I use, it happens even with 1h showing 1 flip or if I reset all flips, I've sent you an youtube link on your email if you'd like to check it out (didn't want to post it publicly for account info purposes)

**Comment by zumaad** [comment]
Wow, i just saw the video. That is crazy. Do you have discord? If so, message me at flopping#9667. I'll help u export some logs and we can take a look at the problem.

**Comment by zumaad** [comment]
Performance issues due to file size. Going to look at possible ways to speed this up. Closed for now
