### ISSUE TITLE
BUG: Incorrect buy / sell price applied.

### ISSUE THREAD

**Issue by MauriceBenink** [Belieal/flipping-utilities#95]
![image](https://user-images.githubusercontent.com/25739203/88789031-7ebf7e80-d196-11ea-80a0-4c55473690e4.png)

What happend is that i wanted to flip some toolseeds. checked their margins (1.82m was the initial sell price) However the price dropped so i cancled the open offer i had. re-checked the new sell price and had to sell for a small loss. 
However the tool still uses the initial sell price of the previous day, and used the new sell price of this day as buy price. 

This makes it look like i made 15k per item. While im making a loss of about 1 - 2 k. 

P.S. i also left the client open overnight.

**Comment by zumaad** [comment]
Thanks for the bug submission! I'm pretty sure we have a fix for this in v1.4.0 (hasn't been released yet unfortunately), but i'll take another look and let you know

**Comment by MauriceBenink** [comment]
Also is there a way / location to get logs from the plugin ?, I would've loved to include the logs but i had no idea where to find them

**Comment by zumaad** [comment]
they are located in {your home directory}/.runelite/logs

The one that just says "client" and isn't dated like "client_2020-07-22.0" is the most recent one i believe
